### ISSUE TITLE
LEDs turn on in esp deep sleep 

### ISSUE THREAD

**Issue by Grohation** [m5stack/M5Atom#31] opened 2020-12-28 15:55 UTC
Dear people of the M5Atom community,

I have a small issue where the LEDs turn in deep sleep mode after I displayed an image. 

The figures below show my code, a picture of the image (green check) and the LEDs that turn on.

The color of the LEDs differ every time it is in deep sleep. In a different program, the LEDs that turn on differ too. 

Help would be appreciated, thanks in advance!

![image](https://user-images.githubusercontent.com/49251295/103226139-bab86480-492b-11eb-97d0-b4b3e50c8b60.png)

![image](https://user-images.githubusercontent.com/49251295/103226163-c9068080-492b-11eb-9e10-bfa32c29f8e1.png)

![image](https://user-images.githubusercontent.com/49251295/103226707-09b2c980-492d-11eb-886a-9df1ce06c97a.png)

![image](https://user-images.githubusercontent.com/49251295/103226428-6497f100-492c-11eb-8a44-88ee46a82aab.png)

**Comment by Tinyu-Zhao** [comment] 2022-07-19 02:25
Sorry, I don't know why I didn't reproduce your question, I will close it because the issue is too old, if you have more questions feel free to ask.

https://user-images.githubusercontent.com/44396641/179650716-83908750-e5d2-40e7-ac2b-975056de0e7e.MOV

**Closed by Tinyu-Zhao** 2022-07-19 02:25 UTC
